name: Revalidate pages

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  call_api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Call /analytics API and display response
        env:
          REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}
        run: |
          RESPONSE=$(curl -X GET "https://voltwise.vercel.app/api/revalidate/analytics?secret=${REVALIDATE_TOKEN}")
          echo "/analytics Response: $RESPONSE"

      - name: Call /plot API and display response
        env:
          REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}
        run: |
          RESPONSE=$(curl -X GET "https://voltwise.vercel.app/api/revalidate/plot?secret=${REVALIDATE_TOKEN}")
          echo "/plot Response: $RESPONSE"

      - name: Call /compare API and display response
        env:
          REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}
        run: |
          RESPONSE=$(curl -X GET "https://voltwise.vercel.app/api/revalidate/compare?secret=${REVALIDATE_TOKEN}")
          echo "/compare Response: $RESPONSE"
