name: Revalidate pages

on:
  schedule:
    - cron: "10 10 * * *"

jobs:
  call_api:
    runs-on: ubuntu-latest

    steps:
      - name: Call AWS API and display response
        env:
          AWS_BASE_URL: ${{ secrets.AWS_BASE_URL }}
        run: |
          RESPONSE=$(curl -X GET "${AWS_BASE_URL}/statistics-data?region=CAL&year=2023")
          REGION=$(echo "$RESPONSE" | jq -r .region)
          YEAR=$(echo "$RESPONSE" | jq -r .year)
          echo "AWS Region: $REGION, Year: $YEAR"

      # - name: Call warmup api and display response
      #   env:
      #     REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}
      #   run: |
      #     RESPONSE=$(curl -X GET "https://voltwise.vercel.app/api/warmup?secret=${REVALIDATE_TOKEN}")
      #     echo "Warmup Response: $RESPONSE"

      - name: Call /analytics API and display response
        env:
          REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}
        run: |
          RESPONSE=$(curl -X GET "https://voltwise.vercel.app/api/revalidate/analytics?secret=${REVALIDATE_TOKEN}")
          echo "/analytics Response: $RESPONSE"

      - name: Call /plot API and display response
        env:
          REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}
        run: |
          RESPONSE=$(curl -X GET "https://voltwise.vercel.app/api/revalidate/plot?secret=${REVALIDATE_TOKEN}")
          echo "/plot Response: $RESPONSE"

      - name: Call /compare API and display response
        env:
          REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}
        run: |
          RESPONSE=$(curl -X GET "https://voltwise.vercel.app/api/revalidate/compare?secret=${REVALIDATE_TOKEN}")
          echo "/compare Response: $RESPONSE"
